//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dil {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Layout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Layout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web_Proje.Resources.Layout", typeof(Layout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Sayfa.
        /// </summary>
        public static string Anasayfa {
            get {
                return ResourceManager.GetString("Anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu hesaptan çıkış yapıldı, lütfen daha sonra tekrar deneyin.
        /// </summary>
        public static string BuHesaptan {
            get {
                return ResourceManager.GetString("BuHesaptan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış.
        /// </summary>
        public static string Cikis {
            get {
                return ResourceManager.GetString("Cikis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış Yapıldı.
        /// </summary>
        public static string CikisYapildi {
            get {
                return ResourceManager.GetString("CikisYapildi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekonomi.
        /// </summary>
        public static string Ekonomi {
            get {
                return ResourceManager.GetString("Ekonomi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İngilizce.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş yap.
        /// </summary>
        public static string Giris {
            get {
                return ResourceManager.GetString("Giris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gizlilik Politikası.
        /// </summary>
        public static string GizlilikPolitikasi {
            get {
                return ResourceManager.GetString("GizlilikPolitikasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gündem.
        /// </summary>
        public static string Gundem {
            get {
                return ResourceManager.GetString("Gundem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HABERLER.
        /// </summary>
        public static string Haberler {
            get {
                return ResourceManager.GetString("Haberler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haberleri Listele.
        /// </summary>
        public static string HaberleriListele {
            get {
                return ResourceManager.GetString("HaberleriListele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Hakları Saklıdır.
        /// </summary>
        public static string Hak {
            get {
                return ResourceManager.GetString("Hak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        public static string Hakkimizda {
            get {
                return ResourceManager.GetString("Hakkimizda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata.
        /// </summary>
        public static string Hata {
            get {
                return ResourceManager.GetString("Hata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu site BURAK BAYRAM tarafından hazırlanmıştır.
        /// </summary>
        public static string Hazir {
            get {
                return ResourceManager.GetString("Hazir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        public static string Iletisim {
            get {
                return ResourceManager.GetString("Iletisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşleminiz gerçekleştirilirken bir hata oluştu.
        /// </summary>
        public static string Isleminiz {
            get {
                return ResourceManager.GetString("Isleminiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoriler.
        /// </summary>
        public static string Kategoriler {
            get {
                return ResourceManager.GetString("Kategoriler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magazin.
        /// </summary>
        public static string Magazin {
            get {
                return ResourceManager.GetString("Magazin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merhaba .
        /// </summary>
        public static string Merhaba {
            get {
                return ResourceManager.GetString("Merhaba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reklam.
        /// </summary>
        public static string Reklam {
            get {
                return ResourceManager.GetString("Reklam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolleri Listele.
        /// </summary>
        public static string RolleriListele {
            get {
                return ResourceManager.GetString("RolleriListele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siyaset.
        /// </summary>
        public static string Siyaset {
            get {
                return ResourceManager.GetString("Siyaset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sosyal Medya.
        /// </summary>
        public static string SosyalMedya {
            get {
                return ResourceManager.GetString("SosyalMedya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spor.
        /// </summary>
        public static string Spor {
            get {
                return ResourceManager.GetString("Spor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe.
        /// </summary>
        public static string Turkce {
            get {
                return ResourceManager.GetString("Turkce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye ol.
        /// </summary>
        public static string Uye {
            get {
                return ResourceManager.GetString("Uye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üyeleri Listele.
        /// </summary>
        public static string UyeleriListele {
            get {
                return ResourceManager.GetString("UyeleriListele", resourceCulture);
            }
        }
    }
}
